---
version: 1
formatters:
  simple:
    format: '* %(message)s'
  complex:
    format: '%(asctime)-19.19s | %(levelname)s | %(message)s'
handlers:
  file:
    class: logging.FileHandler
    formatter: complex
    level: DEBUG
    filename: debug.log
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
    stream: ext://sys.stdout
loggers:
  kernelLogs:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: NOTSET
  handlers: [console,file]
